// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clnddfgmsilmtavzbehe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsbmRkZmdtc2lsbXRhdnpiZWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjQ2MDQsImV4cCI6MjA3MTU0MDYwNH0.x2aPMxzfOd6dPGUV0nx_lYfUH3M71APn7cJCEXZum7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});